# See https://ods.od.nih.gov/Health_Information/Dietary_Reference_Intakes.aspx
Vitamin A: 900 µg
Vitamin C: 90 mg
Vitamin D: 15 µg
Vitamin E: 15 mg
Vitamin K: 120 µg
Thiamin (B1): 1.2 mg
Riboflavin (B2): 1.3 mg
Niacin (B3): 16 mg
Vitamin B6: 1.3 mg
Folate (Equivalent): 400 µg
Vitamin B12: 2.4 µg

Calcium: 1000 mg
Iron: 8 mg
Magnesium: 400 mg
Phosphorus: 700 mg
Zinc: 11 mg
Potassium: 4700 g
Sodium: 1500 g
