# See https://ods.od.nih.gov/Health_Information/Dietary_Reference_Intakes.aspx
Vitamin A: 900
Vitamin C: 90
Vitamin D: 15
Vitamin E: 15
Vitamin K: 120
Thiamin (B1): 1.2
Riboflavin (B2): 1.3
Niacin (B3): 16
Vitamin B6: 1.3
Folate (Equivalent): 400
Vitamin B12: 2.4

Calcium: 1000
Iron: 8
Magnesium: 400
Phosphorus: 700
Zinc: 11
Potassium: 4700
Sodium: 1500
